# Generated by Django 5.1.6 on 2025-02-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='available_spaces',
            field=models.IntegerField(default=0),
        ),
    ]
