# Generated by Django 5.1.5 on 2025-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(upload_to='parking_images')),
            ],
        ),
        migrations.DeleteModel(
            name='parking_place',
        ),
    ]
