# Generated by Django 5.1.6 on 2025-02-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_parkingplace_available_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='vehicle_reg_no',
        ),
        migrations.AddField(
            model_name='parkingdetails',
            name='vehicle_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='parking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
