# Generated by Django 5.1.6 on 2025-02-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_vehicletype_vehicle_reg_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='parking_fee',
        ),
        migrations.CreateModel(
            name='ParkingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.parkingplace')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicletype')),
            ],
            options={
                'unique_together': {('parking_place', 'vehicle_type')},
            },
        ),
    ]
