# Generated by Django 5.1.6 on 2025-02-10 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_vehicletype_parking_fee_parkingfee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='vehicle_type_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lot_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='parking_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='home.parkingplace'),
        ),
        migrations.AlterField(
            model_name='logdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.user'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_details', to='home.parkinglot'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='occupied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_records', to='home.user'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_details', to='home.parkingplace'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='vehicle_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_vehicles', to='home.vehicletype'),
        ),
        migrations.AlterField(
            model_name='parkingfee',
            name='parking_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='home.parkingplace'),
        ),
        migrations.AlterField(
            model_name='parkingfee',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='home.vehicletype'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='status_after',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='status_before',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='available_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='place_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.parkingdetails'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.user'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
