# Generated by Django 5.1.6 on 2025-02-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_paymentdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='status_after',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='status_before',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='parking_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='home.parkingplace'),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='available_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='place_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AllowedVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_vehicle_types', to='home.parkingplace')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicletype')),
            ],
            options={
                'unique_together': {('parking_place', 'vehicle_type')},
            },
        ),
    ]
