# Generated by Django 5.1.6 on 2025-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_parkinglot_status_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='parking_place',
            new_name='parking_id',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='status',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='status_after',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='status_before',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
