# Generated by Django 5.1.6 on 2025-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_parking_place_parkinglot_parking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='status_after',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='status_before',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
