# Generated by Django 5.1.6 on 2025-02-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_parkinglot_lot_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='parking_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='home.parkingplace'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
