# Generated by Django 5.1.6 on 2025-02-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_parkinglot_parking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='allowed_vehicle_types',
            field=models.ManyToManyField(blank=True, to='home.vehicletype'),
        ),
        migrations.DeleteModel(
            name='AllowedVehicleType',
        ),
    ]
