# Generated by Django 5.1.6 on 2025-02-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_parkingplace_allowed_vehicle_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingplace',
            name='allowed_vehicle_types',
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='AllowedVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_vehicle_types', to='home.parkingplace')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_in_places', to='home.vehicletype')),
            ],
            options={
                'unique_together': {('parking_place', 'vehicle_type')},
            },
        ),
    ]
