# Generated by Django 5.1.6 on 2025-02-19 07:54

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='lot_id',
            new_name='parking_lot',
        ),
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='place_id',
            new_name='parking_place',
        ),
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='vehicle_type_id',
            new_name='vehicle_type',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='logdetails',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Format: YYBH####XX', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='parking_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='home.parkingdetails'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='vehicle_reg_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[home.models.validate_vehicle_number]),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='place_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
