# Generated by Django 5.1.6 on 2025-02-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_user_id_logdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='available_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
