# Generated by Django 5.1.6 on 2025-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_parkingplace_available_spaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
