# Generated by Django 5.1.6 on 2025-02-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogDetails',
        ),
    ]
