# Generated by Django 5.1.6 on 2025-02-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_logdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingplace',
            name='available_spaces',
        ),
    ]
