# Generated by Django 5.1.6 on 2025-02-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_parkingplace_available_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='lot_name',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='status_after',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='status_before',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lot_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='parking_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.parkingplace'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
