# Generated by Django 5.1.6 on 2025-03-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_parkinglot_lot_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingplace',
            name='capacity',
        ),
    ]
