# Generated by Django 5.1.6 on 2025-03-01 13:22

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_parkingplace_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='occupied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='parking_lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.parkinglot'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='parking_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='vehicle_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[home.models.validate_vehicle_number]),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='vehicle_type',
            field=models.CharField(max_length=20),
        ),
    ]
