# Generated by Django 5.1.6 on 2025-03-01 13:38

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_parkingdetails_vehicle_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='vehicle_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[home.models.validate_vehicle_number]),
        ),
    ]
