# Generated by Django 5.1.6 on 2025-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_parkingdetails_vehicle_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
