# Generated by Django 5.1.6 on 2025-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_parkinglot_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
