# Generated by Django 5.1.6 on 2025-03-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_parkingdetails_alter_paymentdetails_parking_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingdetails',
            name='vehicle_type_id',
        ),
        migrations.AddField(
            model_name='parkingdetails',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.vehicletype'),
        ),
    ]
