# Generated by Django 5.1.6 on 2025-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_parkingdetails_vehicle_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='occupied_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
