# Generated by Django 5.1.6 on 2025-03-10 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_parkingdetails_occupied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
