# Generated by Django 5.1.6 on 2025-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_parkinglot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
