# Generated by Django 5.1.6 on 2025-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_parkinglot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
