# Generated by Django 5.1.6 on 2025-03-10 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_parkingdetails_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
