# Generated by Django 5.1.6 on 2025-03-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_parkingdetails_authorized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.parkinglot'),
        ),
    ]
