# Generated by Django 5.1.6 on 2025-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_parkingdetails_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
