# Generated by Django 5.1.6 on 2025-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_parkingdetails_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
