# Generated by Django 5.1.6 on 2025-03-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_parkingdetails_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='home.parkinglot'),
        ),
    ]
